### ISSUE TITLE
Failure in CLI fetch of relaton-iana

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#3]
Somehow it's working in bibxml-data-iana but failing when I run locally?

```
relaton fetch-data iana-registries
[relaton] Info: detecting backends:
/Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-cli-1.9.3/lib/relaton/cli/data_fetcher.rb:9:in `fetch': undefined method `fetch_data' for nil:NilClass (NoMethodError)
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-cli-1.9.3/lib/relaton/cli/command.rb:150:in `fetch_data'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:71:in `block in run'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/hollaback-0.1.1/lib/hollaback/sequence.rb:34:in `call'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:71:in `run'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-cli-1.9.3/lib/relaton/cli.rb:41:in `start'
	from /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-cli-1.9.3/exe/relaton:20:in `<top (required)>'
	from /Users/me/.rbenv/versions/3.0.2/bin/relaton:23:in `load'
	from /Users/me/.rbenv/versions/3.0.2/bin/relaton:23:in `<main>'
```

**Comment by andrew2net** [comment]
fixed in v 1.9.1
