### ISSUE TITLE
(URGENT) Failed cron run due to changed data

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#4]
https://github.com/relaton/relaton-data-iana/runs/4740219912?check_suite_focus=true

```
[relaton] Info: detecting backends:
7
File data/phbid-codes.yaml already exists. Document: phbid-codes
8
/opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:39:in `fetch': undefined method `each' for nil:NilClass (NoMethodError)
9

10
      json["items"].each do |item|
11
                   ^^^^^
12
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
13
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
14
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
15
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
16
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
17
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
18
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
19
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
20
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
21
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:42:in `fetch'
22
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/data_fetcher.rb:26:in `fetch'
23
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-iana-1.9.0/lib/relaton_iana/processor.rb:32:in `fetch_data'
24
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-cli-1.9.5/lib/relaton/cli/data_fetcher.rb:9:in `fetch'
25
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-cli-1.9.5/lib/relaton/cli/command.rb:150:in `fetch_data'
26
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
27
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:71:in `block in run'
28
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/hollaback-0.1.1/lib/hollaback/sequence.rb:34:in `call'
29
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:71:in `run'
30
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
31
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
32
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
33
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-cli-1.9.5/lib/relaton/cli.rb:41:in `start'
34
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0/gems/relaton-cli-1.9.5/exe/relaton:20:in `<top (required)>'
35
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/bin/relaton:25:in `load'
36
	from /opt/hostedtoolcache/Ruby/3.1.0/x64/bin/relaton:25:in `<main>'
37
Started at: 2022-01-07 15:08:27 +0000
38
```

**Comment by andrew2net** [comment]
I don't know why it used an old version of rlaton-iana. After removing the old version from RubyGems index it uses the latest and works correctly.
